# Generated by Django 3.2.7 on 2022-03-07 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_tokensprocedures'),
    ]

    operations = [
        migrations.CreateModel(
            name='Descripciones_y_sinonimos',
            fields=[
                ('id', models.CharField(max_length=18, primary_key=True, serialize=False)),
                ('active', models.CharField(max_length=1)),
                ('conceptid', models.CharField(max_length=18)),
                ('typeid', models.CharField(max_length=18)),
                ('term', models.CharField(max_length=255)),
                ('category_id', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
