# Generated by Django 3.2.7 on 2022-03-09 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_descripciones_y_sinonimos_category_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='TokensDiagnosticosYSinonimos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=255)),
                ('id_descripcion', models.CharField(max_length=255)),
                ('largo_palabras_termino', models.IntegerField()),
            ],
        ),
    ]
